# Generated by Django 4.2 on 2025-11-18 11:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_number', models.CharField(max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='IN', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('personal_auto', 'Personal Auto'), ('homeowners', 'Homeowners'), ('term_life', 'Term Life'), ('health', 'Health'), ('other', 'Other')], default='other', max_length=40)),
                ('base_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(max_length=10)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'policy_catalog',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_number', models.CharField(max_length=60, unique=True)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('quoted', 'quoted'), ('issued', 'issued'), ('active', 'active'), ('cancelled', 'Refunded'), ('lapsed', 'Lapsed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.customer')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.policy')),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['policy_code'], name='policy_cata_policy__f26c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['category'], name='policy_cata_categor_e79d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['is_active'], name='policy_cata_is_acti_d8d15b_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_number'], name='customer_custome_69d17f_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='customer_last_na_c66c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchase_number'], name='purchase_purchas_934456_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['customer'], name='purchase_custome_44f284_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['policy'], name='purchase_policy__7491ff_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchase_date'], name='purchase_purchas_f11d44_idx'),
        ),
    ]
